// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: bootstrap/bootstrap.proto

package bootstrap

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BootstrapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version int64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *BootstrapRequest) Reset() {
	*x = BootstrapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootstrap_bootstrap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapRequest) ProtoMessage() {}

func (x *BootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_bootstrap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapRequest.ProtoReflect.Descriptor instead.
func (*BootstrapRequest) Descriptor() ([]byte, []int) {
	return file_bootstrap_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *BootstrapRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type IncompatibleVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NeedsVersion int64 `protobuf:"varint,1,opt,name=needsVersion,proto3" json:"needsVersion,omitempty"`
}

func (x *IncompatibleVersion) Reset() {
	*x = IncompatibleVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootstrap_bootstrap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncompatibleVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncompatibleVersion) ProtoMessage() {}

func (x *IncompatibleVersion) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_bootstrap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncompatibleVersion.ProtoReflect.Descriptor instead.
func (*IncompatibleVersion) Descriptor() ([]byte, []int) {
	return file_bootstrap_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *IncompatibleVersion) GetNeedsVersion() int64 {
	if x != nil {
		return x.NeedsVersion
	}
	return 0
}

type BootstrapData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version int64  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BootstrapData) Reset() {
	*x = BootstrapData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootstrap_bootstrap_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BootstrapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapData) ProtoMessage() {}

func (x *BootstrapData) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_bootstrap_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapData.ProtoReflect.Descriptor instead.
func (*BootstrapData) Descriptor() ([]byte, []int) {
	return file_bootstrap_bootstrap_proto_rawDescGZIP(), []int{2}
}

func (x *BootstrapData) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BootstrapData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BootstrapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*BootstrapResponse_IncompatibleVersion
	//	*BootstrapResponse_BootstrapData
	Response isBootstrapResponse_Response `protobuf_oneof:"response"`
}

func (x *BootstrapResponse) Reset() {
	*x = BootstrapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootstrap_bootstrap_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapResponse) ProtoMessage() {}

func (x *BootstrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_bootstrap_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapResponse.ProtoReflect.Descriptor instead.
func (*BootstrapResponse) Descriptor() ([]byte, []int) {
	return file_bootstrap_bootstrap_proto_rawDescGZIP(), []int{3}
}

func (m *BootstrapResponse) GetResponse() isBootstrapResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *BootstrapResponse) GetIncompatibleVersion() *IncompatibleVersion {
	if x, ok := x.GetResponse().(*BootstrapResponse_IncompatibleVersion); ok {
		return x.IncompatibleVersion
	}
	return nil
}

func (x *BootstrapResponse) GetBootstrapData() *BootstrapData {
	if x, ok := x.GetResponse().(*BootstrapResponse_BootstrapData); ok {
		return x.BootstrapData
	}
	return nil
}

type isBootstrapResponse_Response interface {
	isBootstrapResponse_Response()
}

type BootstrapResponse_IncompatibleVersion struct {
	IncompatibleVersion *IncompatibleVersion `protobuf:"bytes,1,opt,name=incompatibleVersion,proto3,oneof"`
}

type BootstrapResponse_BootstrapData struct {
	BootstrapData *BootstrapData `protobuf:"bytes,2,opt,name=bootstrapData,proto3,oneof"`
}

func (*BootstrapResponse_IncompatibleVersion) isBootstrapResponse_Response() {}

func (*BootstrapResponse_BootstrapData) isBootstrapResponse_Response() {}

var File_bootstrap_bootstrap_proto protoreflect.FileDescriptor

var file_bootstrap_bootstrap_proto_rawDesc = []byte{
	0x0a, 0x19, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2f, 0x62, 0x6f, 0x6f, 0x74,
	0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x74, 0x6c,
	0x61, 0x73, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x22, 0x2c, 0x0a, 0x10,
	0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x39, 0x0a, 0x13, 0x49, 0x6e,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x65, 0x65, 0x64, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6e, 0x65, 0x65, 0x64, 0x73, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3d, 0x0a, 0x0d, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72,
	0x61, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0xc1, 0x01, 0x0a, 0x11, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72,
	0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x13, 0x69, 0x6e,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2e,
	0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x13, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x46, 0x0a, 0x0d, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61,
	0x70, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x74,
	0x6c, 0x61, 0x73, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x42, 0x6f,
	0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0d, 0x62,
	0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x44, 0x61, 0x74, 0x61, 0x42, 0x0a, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x6a, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x74,
	0x73, 0x74, 0x72, 0x61, 0x70, 0x12, 0x5d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x74,
	0x73, 0x74, 0x72, 0x61, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x2e, 0x61, 0x74, 0x6c, 0x61,
	0x73, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x42, 0x6f, 0x6f, 0x74,
	0x73, 0x74, 0x72, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61,
	0x74, 0x6c, 0x61, 0x73, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x42,
	0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72,
	0x61, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bootstrap_bootstrap_proto_rawDescOnce sync.Once
	file_bootstrap_bootstrap_proto_rawDescData = file_bootstrap_bootstrap_proto_rawDesc
)

func file_bootstrap_bootstrap_proto_rawDescGZIP() []byte {
	file_bootstrap_bootstrap_proto_rawDescOnce.Do(func() {
		file_bootstrap_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(file_bootstrap_bootstrap_proto_rawDescData)
	})
	return file_bootstrap_bootstrap_proto_rawDescData
}

var file_bootstrap_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bootstrap_bootstrap_proto_goTypes = []interface{}{
	(*BootstrapRequest)(nil),    // 0: atlas.bootstrap.BootstrapRequest
	(*IncompatibleVersion)(nil), // 1: atlas.bootstrap.IncompatibleVersion
	(*BootstrapData)(nil),       // 2: atlas.bootstrap.BootstrapData
	(*BootstrapResponse)(nil),   // 3: atlas.bootstrap.BootstrapResponse
}
var file_bootstrap_bootstrap_proto_depIdxs = []int32{
	1, // 0: atlas.bootstrap.BootstrapResponse.incompatibleVersion:type_name -> atlas.bootstrap.IncompatibleVersion
	2, // 1: atlas.bootstrap.BootstrapResponse.bootstrapData:type_name -> atlas.bootstrap.BootstrapData
	0, // 2: atlas.bootstrap.Bootstrap.GetBootstrapData:input_type -> atlas.bootstrap.BootstrapRequest
	3, // 3: atlas.bootstrap.Bootstrap.GetBootstrapData:output_type -> atlas.bootstrap.BootstrapResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bootstrap_bootstrap_proto_init() }
func file_bootstrap_bootstrap_proto_init() {
	if File_bootstrap_bootstrap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bootstrap_bootstrap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BootstrapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bootstrap_bootstrap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncompatibleVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bootstrap_bootstrap_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BootstrapData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bootstrap_bootstrap_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BootstrapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bootstrap_bootstrap_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*BootstrapResponse_IncompatibleVersion)(nil),
		(*BootstrapResponse_BootstrapData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bootstrap_bootstrap_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bootstrap_bootstrap_proto_goTypes,
		DependencyIndexes: file_bootstrap_bootstrap_proto_depIdxs,
		MessageInfos:      file_bootstrap_bootstrap_proto_msgTypes,
	}.Build()
	File_bootstrap_bootstrap_proto = out.File
	file_bootstrap_bootstrap_proto_rawDesc = nil
	file_bootstrap_bootstrap_proto_goTypes = nil
	file_bootstrap_bootstrap_proto_depIdxs = nil
}
