on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
    contents: write
    pull-requests: write

jobs:
  auto-merge:
    runs-on: self-hosted
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge Dependabot PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.WITHINBOREDOM_GH_PAT }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '@dependabot squash and merge'
            })
